######################################################################
##
## Filename: ee254_numlock_sm_tb.udo
## Created on: Sun Nov 30 12:33:44 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
