######################################################################
##
## Filename: hvsync_tb.udo
## Created on: Sun Nov 30 2:59:24 PM Pacific Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
